### ISSUE TITLE
Messy configuration file

### ISSUE THREAD

**Issue by samcole8** [samcole8/ysmr#2]
Configuration TOML is not organised by module, and each account (instance) is loaded directly into a list object in the Config class.

This makes the ysmr.toml file messy. Below is a proposed improved layout:

```toml
# ysmr.toml

[module_name]

global_enabled=true

[[module_name.instance]]
id="alice"
enabled=true
option="example1"

[[module_name.instance]]
id="bob"
enabled=false
option="example2"

```

ysmr.py will need to be updated to interface with any new structure.
